### ISSUE TITLE
Machine Learning Data Scrape: Ratings Data

### ISSUE THREAD

**Issue by muhammadhafizmm** [Bangkit-C22-HO04/ML-Research#1]
## Ratings Data
Combination of ratings/review by user and the user’s data, just like the example above.
Curate reviews with high rating and low rating.

**Todo:**
- [x] scrape hotel data :
- hotel_id :heavy_check_mark:
- nama_hotel :heavy_check_mark:
- [x] scrape hotel review data :
- user data: 
    - user_id :heavy_check_mark:
    - name :heavy_check_mark:
    - gender (?)
    - location (?)
- review hotel  :heavy_check_mark:
- rating hotel  :heavy_check_mark:
- Travel purpose  :heavy_check_mark:
- [x] store all data to csv 
- [x] export data

 [Colab link](https://colab.research.google.com/drive/1lrTkBZbOrUWiYnkyWocQymfphbO2DPG-#scrollTo=zs7xZlJNPpiZ)
